# Generated by Django 5.0.2 on 2024-02-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_calzados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calzados',
            new_name='Calzadoss',
        ),
    ]
