# Generated by Django 5.0.2 on 2024-02-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_calzados_calzadoss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzadoss',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
