# Generated by Django 5.0.2 on 2024-02-14 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_imagess_image_alter_imagess_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagess',
            name='title',
        ),
        migrations.AddField(
            model_name='imagess',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.pedido'),
            preserve_default=False,
        ),
    ]
