# Generated by Django 5.0.2 on 2024-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_imagess_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagess',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='imagen', width_field=300),
        ),
    ]
