# Generated by Django 5.0.2 on 2024-02-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_imagess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagess',
            name='height_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='imagess',
            name='width_field',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='imagess',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
